export const sidebarStyles = {
  shell: {
    width: "280px",
    minWidth: "280px",
    backgroundColor: "#09121a",
    color: "#f8fafc",
    boxShadow: "0 10px 30px rgba(2, 8, 23, 0.25)",
    position: "sticky",
    top: 0,
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    boxSizing: "border-box",
    overflow: "hidden",
    transition: "transform 0.3s ease",
    zIndex: 30,
  },
  mobileTopBar: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "#09121a",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.2)",
    zIndex: 35,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: "72px",
    padding: "0 1rem",
  },
  mobileLogo: {
    width: "220px",
    height: "auto",
    margin: 0,
    display: "block",
  },
  hamburgerButton: {
    cursor: "pointer",
    padding: "8px",
    position: "absolute",
    left: "1rem",
    color: "#ffffff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    background: "rgba(2, 6, 23, 0.6)",
    zIndex: 29,
  },
  header: {
    padding: "22px 20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
  },
  logo: {
    width: "100%",
    maxWidth: "290px",
    height: "130px",
    objectFit: "cover",
    display: "block",
    margin: "auto",
  },
  welcomeText: {
    margin: 0,
    color: "#cbd5e1",
    fontSize: "0.9rem",
    textAlign: "center",
  },
  nav: {
    padding: "14px 10px 16px",
    flex: "1 1 auto",
    overflowY: "auto",
    WebkitOverflowScrolling: "touch",
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "11px 14px",
    cursor: "pointer",
    color: "#dbe5f3",
    borderRadius: "12px",
    transition: "all 0.2s ease",
    marginBottom: "6px",
  },
  menuItemActive: {
    backgroundColor: "#1e2f41",
    color: "#ffffff",
  },
  menuItemContent: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  menuIcon: {
    color: "#9fb4c8",
  },
  menuText: {
    fontSize: "0.92rem",
    fontWeight: "500",
  },
  submenu: {
    overflow: "hidden",
    borderLeft: "2px solid rgba(159, 180, 200, 0.25)",
    marginLeft: "14px",
    marginBottom: "8px",
  },
  submenuItem: {
    padding: "9px 12px 9px 18px",
    cursor: "pointer",
    color: "#b9c8d8",
    fontSize: "0.86rem",
    borderRadius: "10px",
    margin: "3px 0 3px 8px",
    transition: "all 0.2s ease",
  },
  submenuItemActive: {
    backgroundColor: "#1a2a3a",
    color: "#ffffff",
  },
  logoutButton: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 14px",
    cursor: "pointer",
    color: "#fca5a5",
    marginTop: "12px",
    borderTop: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "12px",
  },
};
